name: Screenshot

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL'
        required: true
        type: string

jobs:
  shot:
    runs-on: ubuntu-latest
    steps:
      - name: Make folder
        run: mkdir -p Shots

      - name: Take screenshot with curl
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          chromium-browser --headless --disable-gpu --screenshot=Shots/output.png --window-size=1280,800 ${{ github.event.inputs.url }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: Shots/
